- id: 4
  name: "dharamshala dalhousie tour package"
  qty: 2
  price: 10000.00
  login_id: 1

- id: 3
  name: "Shimla Holiday Tour Package"
  qty: 1
  price: 6000.00
  login_id: 1

- id: 1
  name: "Shimla Manali 4N 5D Honeymoon Tour Package"
  qty: 1
  price: 10000.00
  login_id: 1

